### ISSUE TITLE
[Bug] LEFT/RIGHT_STICK_MODE = SCROLL_WHEEL doesn't work in JSM 3.5.0

### ISSUE THREAD

**Issue by Someone65** [Electronicks/JoyShockMapper#106]
Running on Win 11 64 bit, I can verify it still works in the previous version but does nothing in 3.5.0. Binding scroll wheel to buttons or the stick works fine so it's just this specific joystick mode that has an issue.

**Comment by Electronicks** [comment]
Fixed in v3.5.1
