### ISSUE TITLE
[Bug] CALIBRATE_TRIGGERS doesn't work

### ISSUE THREAD

**Issue by kurushimee** [Electronicks/JoyShockMapper#110]
Trying to calibrate adaptive triggers on v3.5.2 results in failure.

Calibration starts correctly, but pressing d-pad down results in adaptive trigger motors somehow "twitching" back and worth indefinitely, and pressing on the trigger will result in JSM crashing.

**Comment by Electronicks** [comment]
Please try the latest version v3.5.4
