### ISSUE TITLE
Polling rate optimization

### ISSUE THREAD

**Issue by mirh** [Electronicks/JoyShockMapper#115]
We do know the [highest achievable](https://ryochan7.github.io/ds4windows-site/troubleshooting/input-delay-bt/#usual-controller-latency) reporting frequencies for all the major controllers (putting aside that they may have then their special [knobs](https://github.com/torvalds/linux/commit/58feecb4172b49ad1459e57556667a59df5bdda2) and [levers](https://douevenknow.us/post/159446741358/picking-apart-the-joy-con-charging-joy-con-grip)). 
Now, I don't really have a horse in the likely race between latency and battery (and I don't know, stability too perhaps?), but if the maximum the connected hardware can do is X then it seems just wasteful for the software to update every X/5.

**Comment by JibbSmart** [comment]
If the player's monitor has a higher refresh rate, it's better to match it (or exceed it) to make sure the camera/cursor moves with every new rendered frame

**Comment by Electronicks** [comment]
JSM uses SDL2 as the background controller processing engine. It polls at 1kHz (1ms period) maximum which should be plenty for all common use case. It is also great for low polling rate controllers such as first party switch controllers as JSM controls the update speed, not the controller. If polling at the controller's speed is important, JSM_legacy uses a custom backend called JoyShockLibrary with limited controller support and functionalities, but does process updates as soon as they are avialable.

Please use whichever version suits your needs.
