### ISSUE TITLE
3.1.0+ SDL2 Version Crashes on Windows 10 

### ISSUE THREAD

**Issue by pie75** [Electronicks/JoyShockMapper#12]
The SDL2 Versions of 3.1.0 and 3.1.1 Crash almost immediately. 
No commands appear in the command line before the crash. 
![image](https://user-images.githubusercontent.com/44603413/120233898-137f8680-c257-11eb-8ecb-c21dce73de9a.png)
It probably crashes before being able to load OnStartup.txt, as the absence of the file has no effect.
JSL/Legacy versions of 3.1.0 and 3.1.1, as well as all versions of 3.0.2, 3.0.1, 3.0.0, do not crash.

My PC is 64bit, but if the 64bit version crashes, or runs, the 32bit version performs the same.
OS: Windows 10 Home 1909 build 18363.1440
I understand that my Windows installation is not exactly up-to-date, but I don't think this is the problem.
I can provide more information/perform more tests if necessary.

**Comment by pie75** [comment]
As mentioned in the discord:
My controller is a first-party DS4 v2, connected via USB2.0, not bluetooth.
JSM running does not seem to affect the controller at all, no shut-down, or restart, the light remains on, without blinking or flashing, and the input and connection have no interruption on gamepad-tester.com.

**Comment by Electronicks** [comment]
Two quick questions: 

1. How do you launch JSM when you reproduce this crash? Is it through the windows search bar? A shortcut? Or a double click on the executable?
2. Can you check in the windows controller page (Set USB Game Controllers) the listing of controllers you have? I expect only a Wireless Controller being your DS4, but there could be leftover vigem controllers or some other device that we may not be aware of.

**Comment by pie75** [comment]
1. I launch JSM by double-clicking the executable.
2. There are two devices, Wireless Controller, and a vJoy Device.
I forgot I had that installed. Disabling it does seem to prevent crashing.

**Comment by Electronicks** [comment]
Aha! Well that's good to know. I'll try to see if I can reproduce this myself with a vjoy virtual device. JSM should properly ignore those virtual devices instead of crashing
