### ISSUE TITLE
It's possible to use MOTION_STICK_MODE by rotating instead of tilting?

### ISSUE THREAD

**Issue by Festiu** [Electronicks/JoyShockMapper#121]
Hi there,

I am trying to get MOTION_STICK_MODE = LEFT_STICK to work by rotating the pad and not tilting it, is that possible?

Like setting GYRO_SPACE = PLAYER_TURN instead of PLAYER_LEAN, but for MOTION_STICK in this case.

**Comment by JibbSmart** [comment]
It's probably not possible, because there's no absolute point of reference for turning. It needs the absolute reference of gravity.

**Comment by Festiu** [comment]
Oh I see... I was just wondering. Thanks for replying.
