### ISSUE TITLE
[Feature] Fake device input for Valorant and CS2 Faceit...

### ISSUE THREAD

**Issue by lVentus** [Electronicks/JoyShockMapper#132]
Hi, Because these games doesn't recieve the virtual device input signal, Will we have similar solution like Rewasd? Fake the input as MNK raw input.
Rewasd are seen as cheating software by lots of game studio, there is a risk use it to play these games.
But JSM is fine. So if this is possible, it is so good.

**Comment by Electronicks** [comment]
I looked into it and it is not a trivial addition. So it is not planned right now.
If ReWASD is considered cheating, I'm sure JSM with such a feature will be considered cheating too...

**Comment by lVentus** [comment]
> I looked into it and it is not a trivial addition. So it is not planned right now. If ReWASD is considered cheating, I'm sure JSM with such a feature will be considered cheating too...

Rewasd is considered as cheating not because the fake device input feature.
Because it can convert mouse and keyboard signal to controller signal. So players can use mouse with aim assist.
But JSM only concerns controller input, so it won't be  considered cheating.
