### ISSUE TITLE
[Feature] `TOUCHCLICK` Binding (DualSense/Shock 4/5)

### ISSUE THREAD

**Issue by Jazztache** [Electronicks/JoyShockMapper#134]
Hello!

I recently had an issue on JoyShockMapper. I was testing with some friends, and one of them pressed down on the DualSense 5's touchpad. This caused the `CAPTURE` binding to fire.

The DualSense 5's touchpad isn't a capture or screenshot button, so instead it would be preferable if there was a dedicated binding for it.

This was tested on the Linux version of JSM, but if this is already the case on Windows, then I am happy to revise this report as a bug rather than a feature request.

Thankyou for your consideration!

**Comment by Electronicks** [comment]
That is intended behaviour. I avoid having buttons that are controller specific, so that configs can work across devices.

**Comment by Jazztache** [comment]
I had a use case where someone wanted to use the in-built trackpad support that Linux has for the DualShock5 touchpad alongside  JSM's controls. When he went to use Mouse 1 with the trackpad, he held it down, and it ended up repeatedly screenshotting within the game.

This is really annoying, as now I cannot use the trackpad with CAPTURE bound. It interferes and conflicts with native support for a feature. A `TOUCHCLICK` button solves this problem.

Wouldn't it make more sense for the MIC button to be capture? That would make a lot more sense since it's under the PS button which is bound to HOME. That would also avoid having a specific binding, the 'MIC' button *is* a controller-specific binding. Not even the DS4, the previous iteration of the DualSense 5 has it.
