### ISSUE TITLE
when sending HOME, if numlock is on it sends 7

### ISSUE THREAD

**Issue by kikiwako** [Electronicks/JoyShockMapper#20]
Pretty much self explanatory I think.
If I turn off the numlock it works as expected.
(reminder that pressing 7 on the numpad without numlock sends "Home" 😉)

I am using a right joycon and this configuration:

> RESET_MAPPINGS
> REAL_WORLD_CALIBRATION = 5.33
> IN_GAME_SENS = 1
> COUNTER_OS_MOUSE_SPEED`
> 
> MIN_GYRO_SENS = 3 3
> MAX_GYRO_SENS = 4 4
> GYRO_CUTOFF_RECOVERY = 5
> MIN_GYRO_THRESHOLD = 5
> MAX_GYRO_THRESHOLD = 75
> GYRO_SMOOTH_THRESHOLD = 5
> 
> RIGHT_STICK_MODE = AIM
> STICK_SENS = 350 350
> STICK_POWER = 1
> STICK_ACCELERATION_RATE = 0
> 
> R = RMOUSE
> ZR = LMOUSE
> 
> RSR = HOME
> RSL = ^GYRO_OFF
> 
> W = \LSHIFT LMOUSE /LSHIFT
> N = MMOUSE
> E = SCROLLUP SCROLLUP+
> S = SCROLLDOWN SCROLLDOWN+
> 
> \+ = ENTER
> R3 = NONE
> HOME = NONE

**Comment by Electronicks** [comment]
Fixed in v3.2.2
