### ISSUE TITLE
Can't have right stick and gyro both control right stick

### ISSUE THREAD

**Issue by lyahdav** [Electronicks/JoyShockMapper#31]
I have the config below on v3.2.2 and I'm trying to make it so my Nintendo Switch Pro Controller will show up as an Xbox controller where the right stick and gyro both emulate right stick movement. The gyro works fine with this config but the right stick doesn't map to right stick movement.
```
VIRTUAL_CONTROLLER = XBOX

UP = X_UP
DOWN = X_DOWN
LEFT = X_LEFT
RIGHT = X_RIGHT
L = X_LB
R = X_RB
W = X_X
S = X_A
N = X_Y
E = X_B
L3 = X_LS
R3 = X_RS
- = X_BACK
+ = X_START
HOME = X_GUIDE
ZL_MODE = X_LT
ZR_MODE = X_RT
LEFT_STICK_MODE = LEFT_STICK
RIGHT_STICK_MODE = RIGHT_STICK
MOTION_STICK_MODE = RIGHT_STICK
```

**Comment by Electronicks** [comment]
Next release will have this fix in a way that multiple sources of "right sticks" are added together instead of prioritizing gyro

**Comment by lyahdav** [comment]
I just built from source and confirmed it works, thanks!
