### ISSUE TITLE
RIGHT_STICK_DEADZONE_INNER seems to do nothing for virtual Xbox controller using Nintendo Switch Pro controller gyro for right stick

### ISSUE THREAD

**Issue by lyahdav** [Electronicks/JoyShockMapper#32]
I have the following config:
```
VIRTUAL_CONTROLLER = XBOX

UP = X_UP
DOWN = X_DOWN
LEFT = X_LEFT
RIGHT = X_RIGHT
L = X_LB
R = X_RB
W = X_X
S = X_A
N = X_Y
E = X_B
L3 = X_LS
R3 = X_RS
- = X_BACK
+ = X_START
HOME = X_GUIDE
ZL_MODE = X_LT
ZR_MODE = X_RT
LEFT_STICK_MODE = LEFT_STICK
RIGHT_STICK_MODE = RIGHT_STICK
MOTION_STICK_MODE = RIGHT_STICK
MOTION_DEADZONE_INNER = 1
```
When I move the gyro to control the right stick there's a large deadzone. I already set MOTION_DEADZONE_INNER to a small value. I think the problem is that the virtual controller's right stick has a high deadzone, so I tried setting `RIGHT_STICK_DEADZONE_INNER = 0.01` but that doesn't seem to do anything.

**Comment by Electronicks** [comment]
RIGHT_STICK_DEADZONE_INNER applies to your controller's right stick, not the virtual one. 
It's very likely that the game you are playing has in itself a inner deadzone setting. JSM will send the game little right stick movement (controlled from your gyro) but masks it. You can see in the windows controller page that JSM sends the right stick motion properly or not. Can you confirm my hypothesis?

**Comment by lyahdav** [comment]
You were correct about that hypothesis, thanks!
