### ISSUE TITLE
Can't use GYRO_SENS with MOTION_STICK_MODE = RIGHT_STICK

### ISSUE THREAD

**Issue by lyahdav** [Electronicks/JoyShockMapper#33]
I have the following config:
```
VIRTUAL_CONTROLLER = XBOX

UP = X_UP
DOWN = X_DOWN
LEFT = X_LEFT
RIGHT = X_RIGHT
L = X_LB
R = X_RB
W = X_X
S = X_A
N = X_Y
E = X_B
L3 = X_LS
R3 = X_RS
- = X_BACK
+ = X_START
HOME = X_GUIDE
ZL_MODE = X_LT
ZR_MODE = X_RT
LEFT_STICK_MODE = LEFT_STICK
RIGHT_STICK_MODE = RIGHT_STICK
MOTION_STICK_MODE = RIGHT_STICK
```
If I then try to input `GYRO_SENS = 2` it resets the gyro to control the mouse. Is there another way to set gyro sensitivity with this config?

**Comment by BraqueDown** [comment]
I guess JSM assumes that `GYRO_SENS` would be defined in the config directly after calibration and before everything else. 

Motion Stick doesn't actually use `GYRO_SENS` at all.

From the README:
> - MOTION_DEADZONE_INNER (default 15°) - How far the controller needs to be tilted in order to register as non-zero.
> - MOTION_DEADZONE_OUTER (default 135°) - How far from the maximum rotation will be considered a full tilt. The maximum rotation is of course 180°, so the default value of 135° means tilting at or above 45° from the neutral position will be considered "full tilt".

**Comment by lyahdav** [comment]
So then how can I control the gyro sensitivity without affecting the right stick sensitivity since I have both mapped to virtual controller’s right stick?

**Comment by lyahdav** [comment]
Oh wait, I think you’re saying to use MOTION_DEADZONE_OUTER?

**Comment by BraqueDown** [comment]
Yeah, I think that'll do it. Just know that Motion Stick will still do turning over time, and not relative movement like Steam Input's Mouse Joystick.

**Comment by lyahdav** [comment]
I just realized that I want relative movement when using motion stick, since that’s what I’m used to from Steam and feels more natural for FPS games. I’m assuming JSM doesn’t support it now but is this even feasible to build into JSM? It seems to me you’d have to translate changes in the gyro angle into different amounts of movement of the stick, probably based on certain parameters to tweak it. I’d be willing to try coding this if anyone can give me some pointers of where I should look in the codebase.

**Comment by lyahdav** [comment]
Actually I just found that https://www.rewasd.com/ in gyro mode does exactly this. I’m just going to use that for now.

**Comment by Electronicks** [comment]
The motion stick uses the stick settings, not the gyro settings. The confusion is understandable, but as pointed earlier, the motion stick operates independantly from driving the mouse with the gyro.

**Comment by Electronicks** [comment]
I'm closing this issue as it stems from a misunderstanding of the settings.
