### ISSUE TITLE
Anti-Cheat

### ISSUE THREAD

**Issue by And-OnceAgain** [Electronicks/JoyShockMapper#34]
Sorry if this is the wrong place for this, but I was just wondering if you know anything about how anti-cheat softwares might feel about JSM.   I've been using JSM for Destiny 2 gyro aiming for ages and they're getting Battleye Anti-Cheat soon.

**Comment by Electronicks** [comment]
The only anti cheat software to my knowledge that interacts with JSM is the one in Valroant that blocks virtual keyboard and mouse input, thus ignoring the software. ReWASD is the only remapper that works in Valorant thanks to their licensed virtual device.

All other anti cheat software doesn't care at all about JSM or any other mapping-macro software.
