### ISSUE TITLE
The latest build isnt building on linux 

### ISSUE THREAD

**Issue by linusrg1** [Electronicks/JoyShockMapper#38]
Heres the errors I get 

cmake .. -DCMAKE_CXX_COMPILER=clang++ -DSDL=1 -DHIDAPI=ON && cmake --build .
-- Checking for one of the modules 'gtk+-3.0'
-- Checking for one of the modules 'appindicator3-0.1'
CMake Error at /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:707 (message):
  None of the required 'appindicator3-0.1' found
Call Stack (most recent call first):
  cmake/LinuxConfig.cmake:7 (pkg_search_module)
  CMakeLists.txt:8 (include)

-- Checking for one of the modules 'libevdev'
-- JSM version is vHEAD-HASH-NOTFOUND.HEAD-HASH-NOTFOUND.HEAD-HASH-NOTFOUND
-- CPM: adding package SDL2@0 (3b7649c578b1ff98fb3f1c76fc1a586fe75fb617)
CMake Warning (dev) at build/_deps/sdl2-src/cmake/macros.cmake:8 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'HIDAPI'.
Call Stack (most recent call first):
  build/_deps/sdl2-src/CMakeLists.txt:414 (set_option)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- dynamic libasound -> libasound.so.2
-- Checking for module 'jack'
--   No package 'jack' found
-- Checking for module 'libpipewire-0.3>=0.3.20'
--   No package 'libpipewire-0.3' found
-- dynamic libpulse-simple -> libpulse-simple.so.0
-- Checking for module 'esound'
--   No package 'esound' found
-- Checking for modules 'bcm_host;brcmegl'
--   No package 'bcm_host' found
--   No package 'brcmegl' found
-- dynamic libX11 -> libX11.so.6
-- dynamic libXext -> libXext.so.6
-- dynamic libXcursor -> libXcursor.so.1
-- dynamic libXinerama -> libXinerama.so.1
-- dynamic libXi -> libXi.so.6
-- dynamic libXrandr -> libXrandr.so.2
-- dynamic libXrender -> libXrender.so.1
-- Checking for modules 'libdrm;gbm;egl'
--   No package 'libdrm' found
--   No package 'gbm' found
-- Checking for modules 'wayland-client;wayland-scanner;wayland-egl;wayland-cursor;egl;xkbcommon'
--   Found wayland-client, version 1.18.0
--   Found wayland-scanner, version 1.18.0
--   Found wayland-egl, version 18.1.0
--   Found wayland-cursor, version 1.18.0
--   Found egl, version 1.5
--   Found xkbcommon, version 0.10.0
-- Checking for module 'wayland-scanner>=1.15'
--   Found wayland-scanner, version 1.18.0
-- dynamic libwayland-client -> libwayland-client.so.0
-- dynamic libwayland-egl -> libwayland-egl.so.1
-- dynamic libwayland-cursor -> libwayland-cursor.so.0
-- dynamic libxkbcommon -> libxkbcommon.so.0
-- Checking for module 'libdecor-0'
--   No package 'libdecor-0' found
CMake Error at /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:463 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:643 (_pkg_check_modules_internal)
  build/_deps/sdl2-src/cmake/sdlchecks.cmake:701 (pkg_check_modules)
  build/_deps/sdl2-src/CMakeLists.txt:1217 (CheckWayland)

-- Configuring incomplete, errors occurred!
See also "/home/linus/Downloads/JoyShockMapper-master/build/CMakeFiles/CMakeOutput.log".

**Comment by hdansin** [comment]
Same here. I believe this is due to package conflicts between lib-appindicator3 and lib-ayatana-appindicator. On my system (Solus KDE), when I try to install appindicator-devel it says that it cannot because of package conflicts. lib-ayatana is required by steam, so I'm not sure what the solution is. Perhaps the devs could rely on lib-ayatana instead?

I don't know enough about C++ or the structure of the project to know the correct way to fix this.

**Comment by Electronicks** [comment]
Linux is not officially supported. Feel free to contact the community and propose a fix as a Pull Request.
