### ISSUE TITLE
I also tried the linux version from the list of versions, but while it builds, I get this when running it. 

### ISSUE THREAD

**Issue by linusrg1** [Electronicks/JoyShockMapper#39]
(JoyShockMapper:80786): Gdk-CRITICAL **: 13:13:37.049: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

**Comment by linusrg1** [comment]
nvm

**Comment by Electronicks** [comment]
Linux is not officially supported. Feel free to contact the community and propose a fix as a Pull Request.
