### ISSUE TITLE
Issue with Instant Binding Modifier "!"

### ISSUE THREAD

**Issue by And-OnceAgain** [Electronicks/JoyShockMapper#4]
Hey there, 

I've made a binding that is 

N = !/_ E_ # Binding

My understanding is that means when I hold "N" for hold press time, "/" should tap on and off once, and "E" should hold out until I release "N".   But with that binding, when I hold "N", "/" doesn't key up until I release "N".

That's my main issue, but that's a fallback binding actually.   My initial problem was that with the binding 

N = !/\ E\ # Binding

I was hoping there could be a way to set a small delay before the "E" key down occurs, since "/" brings up a menu, but the menu is animated, so it takes a sec for "E" to be able to be pressed.   

Either way thanks so much for the great work on this :D

**Comment by Electronicks** [comment]
Thank you for the detailed report. Can you try the latest release, 3.1 : I've reworked some of the button activation logic.

Also, the best way to sequence two presses will be with start press and hold presses. You can set the time before hold press activates only on that button this way :
N, HOLD_PRESS_TIME=123 # milliseconds
Instant presses release after 40 ms

**Comment by Electronicks** [comment]
#7 highlighted a similar issue in the current release as well which has been dealt with now.

**Comment by Electronicks** [comment]
Fixed in v3.1.1
