### ISSUE TITLE
Analog Axes Not Working Properly using Dual Joycons on Virtual DS4 Controller

### ISSUE THREAD

**Issue by DamianS-eng** [Electronicks/JoyShockMapper#40]
Simply using the included ds4 example config in v.3.2.3, analog sticks and triggers are not recognized properly when testing Dual Joycons. This is a clip when previewing in Control Panel. Trying to move each analog stick in a clockwise circle, then click each button. Similar behavior when Steam is launched. All digital buttons seem to work fine.
![GameControllers_1](https://user-images.githubusercontent.com/12158234/135944560-bccef0f2-a00d-44f8-ab00-6301c2207d60.gif)

If Virtual Controller is set to Xbox instead, the left analog stick behaves as expected although a little jittery, but Z axis doesn't work for both triggers and right stick is unresponsive.

Seems that for now, the only output mode useful for dual joycons is the original set of keyboard mappings. Is this an implementation problem with ViGEm, or something about the joycon's difference in analog stick deadzones that's causing this behavior?

**Comment by ztk4** [comment]
I have the exact same problem. I'm using a switch pro controller, which I guess is similar enough to dual joycons to cause the same issue.

I've noticed that `LEFT_STICK_AXIS = STANDARD INVERTED` helps a bit by fixing the inverted y-axis behavior I'm also experiencing. But I can't seem to fix the clipping, which is the worst in the x-axis, but also pretty bad in the y-axis.

**Comment by DamianS-eng** [comment]
This issue can be closed. Confirm, as of v.3.3.0, analog sticks and triggers work as expected. Using the ds4.txt template with Dual Joycons. Ignore the lack of center on one of the rotation axes: that right Joycon has stick drift, can be resolved by game.
![output1](https://user-images.githubusercontent.com/12158234/156428540-ef990625-66e0-4fca-848a-f107b2a06a48.gif)
