### ISSUE TITLE
Can't install on arch linux

### ISSUE THREAD

**Issue by lmm1191** [Electronicks/JoyShockMapper#48]
This is the final message after doing a makepkg -si. The one in AUR also do not install.

`20 warnings and 2 errors generated.
make[2]: *** [JoyShockMapper/CMakeFiles/JoyShockMapper.dir/build.make:76: JoyShockMapper/CMakeFiles/JoyShockMapper.dir/src/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:174: JoyShockMapper/CMakeFiles/JoyShockMapper.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
`

**Comment by Electronicks** [comment]
Linux is not officially supported. Feel free to contact the community and propose a fix as a Pull Request.
