### ISSUE TITLE
For Linux users could you PLEASE make a flatpak or SOMETHING for an easier install and setup. 

### ISSUE THREAD

**Issue by linusrg1** [Electronicks/JoyShockMapper#5]
While I know my way around the cli not everyone does and the cmake compile isnt always successful. So it would make things A LOT easier if there was a flatpak or appimage or SOMETHING.

**Comment by linusrg1** [comment]
Guess u dont wanna give Linux users and niceities do you? Too lazy?

**Comment by JibbSmart** [comment]
Nothing lazy about someone maintaining and improving open source software for free. @Electronicks isn't a Linux user. You clearly are. You haven't fixed it. So who's actually lazy?

**Comment by linusrg1** [comment]
> Nothing lazy about someone maintaining and improving open source software for free. @Electronicks isn't a Linux user. You clearly are. You haven't fixed it. So who's actually lazy?
> 
> EDIT: Sorry if that seems harsh. If you didn't realise how ridiculous and entitled it sounds to call this developer lazy -- in spite of all the work he's doing to make this software better, and in spite of him not using the platform you want him to do more work on -- hopefully now you do :)

No, I think both if you just have a total lack of respect for Linux users, and it really pisses me of. You guys probably just test it in windows and are like yup, it works, so it'll probably work in Linux. You guys know that just because Linux and windows both use c++ as a base, that's where the similarities end right? And also no, why should I have to spend weeks learning c++ just to fix errors in a program that I didn't even write. Its YOUR program, YOU fix the errors. Also, the excuse that he doesn't use Linux isn't valid either. Its not that hard to flash Linux to a USB, boot it, and then try to build the program to see if it works or not before he uploads it to github. Doesn't cost him any money either, Linux is free if you didn't know.

**Comment by Electronicks** [comment]
Thank you for your interest in the project. Unfortunately, JoyShockMapper does not officially support Linux. However, Linux support is a common request so it is being taken in consideration. If you'd like to lend a helping hand to bring this software to more users earlier, feel free to join the Gyro Gaming community discord where contributors can help each other.

Otherwise, thank you for your patience.

**Comment by JibbSmart** [comment]
Just to add to @Electronicks point, when it has worked with Linux in the past, this was thanks to Linux users generously contributing their time to make it work. This isn't a half-arsed effort on our part to offer Linux support, but rather other users added Linux support to a Windows project (with Electronicks' help, too).

Please consider that we have limited time of our own, and have to choose what tasks to allocate it to. I'm sure you can understand that we also have worthwhile things to give our own time to. I have just a few hours a week to work on these projects. I'm _still_ working on JoyShockMapper as well as other projects. Electronicks is very generous with his time. And others are being generous with their time, too -- whether with constructive feedback or contributing their own work to improve the program.

**Comment by AL2009man** [comment]
> > Nothing lazy about someone maintaining and improving open source software for free. @Electronicks isn't a Linux user. You clearly are. You haven't fixed it. So who's actually lazy?
> > EDIT: Sorry if that seems harsh. If you didn't realise how ridiculous and entitled it sounds to call this developer lazy -- in spite of all the work he's doing to make this software better, and in spite of him not using the platform you want him to do more work on -- hopefully now you do :)
> 
> No, I think both if you just have a total lack of respect for Linux users, and it really pisses me of. You guys probably just test it in windows and are like yup, it works, so it'll probably work in Linux. You guys know that just because Linux and windows both use c++ as a base, that's where the similarities end right? And also no, why should I have to spend weeks learning c++ just to fix errors in a program that I didn't even write. Its YOUR program, YOU fix the errors. Also, the excuse that he doesn't use Linux isn't valid either. Its not that hard to flash Linux to a USB, boot it, and then try to build the program to see if it works or not before he uploads it to github. Doesn't cost him any money either, Linux is free if you didn't know. Btw none of your builds ever worked on Linux either. So there is defenately something off with the core code, from before it was forked.
> 
> Any who's lazy? Well maybe not him or me , but maybe you? Because you decided to drop the main project from what it seems. And its not that I'm lazy, I'd just rather put my energy into more worthwhile things, like getting more exercise and learning another language for example.
> 
> I hope that this wasn't too harsh. ;)

[Might as well leave this article (written by Mathieu Comandon of Lutris) here](http://mathieu.comandon.org/not-on-the-same-page)...

**Comment by TauAkiou** [comment]
> > Nothing lazy about someone maintaining and improving open source software for free. @Electronicks isn't a Linux user. You clearly are. You haven't fixed it. So who's actually lazy?
> > EDIT: Sorry if that seems harsh. If you didn't realise how ridiculous and entitled it sounds to call this developer lazy -- in spite of all the work he's doing to make this software better, and in spite of him not using the platform you want him to do more work on -- hopefully now you do :)
> 
> No, I think both if you just have a total lack of respect for Linux users, and it really pisses me of. You guys probably just test it in windows and are like yup, it works, so it'll probably work in Linux. You guys know that just because Linux and windows both use c++ as a base, that's where the similarities end right? And also no, why should I have to spend weeks learning c++ just to fix errors in a program that I didn't even write. Its YOUR program, YOU fix the errors. Also, the excuse that he doesn't use Linux isn't valid either. Its not that hard to flash Linux to a USB, boot it, and then try to build the program to see if it works or not before he uploads it to github. Doesn't cost him any money either, Linux is free if you didn't know. Btw none of your builds ever worked on Linux either. So there is defenately something off with the core code, from before it was forked.
> 
> Any who's lazy? Well maybe not him or me , but maybe you? Because you decided to drop the main project from what it seems. And its not that I'm lazy, I'd just rather put my energy into more worthwhile things, like getting more exercise and learning another language for example.
> 
> I hope that this wasn't too harsh. ;)

As one of the people who helps maintain JSM's Linux support, this sort of response from another Linux user is fairly depressing.

JSM is primarily written and maintained by Electronicks with a very small team of supporters who supply patches and work on the project. I'm certain that I'm the only one in the project actively working on and supporting Linux. This is a very small open source project and is, for most intents and purposes, a Windows project in which Linux support has been graciously provided by other members of the community.

That also being said, the developers of any open source project do not owe you anything. All of us are giving our unpaid spare time to contribute to these projects. This is not a matter of 'disrespecting linux users', it is a matter of time and available talent coming in from the community to get things done. Attacking a bunch of people writing software _for free_ and calling the original author lazy because he handed the project off to someone else (which happens very commonly in FOSS) is extremely disrespectful.

Regardless, I do not intend on providing a Flatpak of JSM at this time. Build it from source if you want to use it.
