### ISSUE TITLE
Question: Adaptive Triggers

### ISSUE THREAD

**Issue by snaveevans** [Electronicks/JoyShockMapper#53]
I'm trying to play around with the adaptive triggers and I've been able to easily configure them using `CALIBRATE_TRIGGERS` however I'm trying to use `RIGHT_TRIGGER_EFFECT` and keep getting the error that I'm not configuring it correctly, that it is an invalid value.  So I'm wondering what should the correct value be?  These are what I've tried.

```
# RIGHT_TRIGGER_EFFECT = RESISTANCE 
# RIGHT_TRIGGER_EFFECT = RESISTANCE start[0 9] force[0 8]
# RIGHT_TRIGGER_EFFECT = start[0 9] force[0 8]
# RIGHT_TRIGGER_EFFECT = RESISTANCE start[9] force[8]
# RIGHT_TRIGGER_EFFECT = RESISTANCE start[0 9] force[0 8]: Some resistance starting at point
# RIGHT_TRIGGER_EFFECT = MACHINE start[0 9] end[0 9] force1[0 7] force2[0 7] freq[Hz] period
# RIGHT_TRIGGER_EFFECT = MACHINE
```

**Comment by tnax** [comment]
try this format
`RIGHT_TRIGGER_EFFECT = SEMI_AUTOMATIC 3 6 8`

**Comment by snaveevans** [comment]
Perfect! thank you.

**Comment by snack0verflow** [comment]
@snaveevans sorry about this naive query but how do you even know when to use adaptive triggers, isn't it something that the game should decide? like when firing a gun or pulling a bow? what is the point of setting this from JSM? do you make action items such that only when in ADS it will use resistance mode? if you are a developer and implementing this in your own game then it makes sense but as a player I am confused what can I possibly do with adaptive triggers in JSM
