### ISSUE TITLE
"BOW" Trigger effect doesn't go all the way down

### ISSUE THREAD

**Issue by Crysambrosia** [Electronicks/JoyShockMapper#61]
The DualSense is definitely able to provide resistance all the way down, as proven by using NO_FULL trigger mode with the default trigger effect. Yet the BOW trigger effect stops short of a full pull, even when the "end" parameter is set to its maximum value of 8. As far as I can tell, this is completely unaffected by the Trigger Calibration (the macro is broken btw, see my other report)

**Comment by Electronicks** [comment]
I don't think the BOW effect is meant to go all the way down, it simulates increased tension until the "arrow is released" on the full pull. This is a mechanism built-in the dualsense firmware, I have no control over it unfortunately.
