### ISSUE TITLE
Can not map to arrow keys since v3.2.2

### ISSUE THREAD

**Issue by Tw5EjGDE** [Electronicks/JoyShockMapper#66]
Mapping arrow keys worked in v3.2.1 and before, but not in the later versions.

**Comment by DamianS-eng** [comment]
I can't replicate the problem.

> N = UP
> W = LEFT
> E = RIGHT
> S = DOWN

This works in v.3.3.0. Check your config.

**Comment by Tw5EjGDE** [comment]
Seems like the arrow key binds do work in Explorer, but once I enter a game they stop working.
