### ISSUE TITLE
Map button to multiple keys

### ISSUE THREAD

**Issue by Tw5EjGDE** [Electronicks/JoyShockMapper#67]
Some console games have use and reload on the same button, while the keyboard has them as two separate keys.
I would like to be able to bind Square to press both E and R at the same time without hold or chorded press.

**Comment by DamianS-eng** [comment]
Agreed, I don't see the functionality often demonstrated, but for the example you described, that's a terrible way to implement this feature. Do you want to reload EVERY TIME you interact? In fast-paced games, no you do not.

[Look at the readme section under Tap & Hold:](https://github.com/Electronicks/JoyShockMapper#11-tap--hold) Even in Apex Legends when Square is mapped to two functions, the solution is a decision between a long press for whichever is considered the more relaxed function. This is the equivalent in game:

> W = R E
Tapping Square does the reload, and holding it does the Use function. If you consider Reload the more relaxed, use instead:
> W = E R

If you need the second function active immediately, or if you absolutely must have a output of two simultaneous keys, which is very rare and is normally poorly designed for keyboard use, use the instant (!) action modifier. There is a buffer of time under which the next key must be pressed after the first to be recognized as a new function. It's impossible for a human to press two keys at exactly the same time every intended time. Take advantage of this.

**Comment by Electronicks** [comment]
You may bind two different keys on the same event by applying the same event modifier to both:
S = A\ B\ # Hit keys A and B when I press S
