### ISSUE TITLE
V3.3.0 not running on Pop OS 21.10

### ISSUE THREAD

**Issue by Snorelaxed** [Electronicks/JoyShockMapper#68]
I have followed new instructions added in PR #56 to build the project and also applied changes suggested in PR #56.
Pleased to see It does build.
While I'm trying to run it with a dualsense connected via Bluetooth, the following is the output.
```sh
AUTOLOAD is available. Files in /root/.config/JoyShockMapper/AutoLoad/ folder will get loaded automatically when a matching application is in focus.
1 device connected
Resetting all mappings to defaults
There is no OnReset.txt file to load.
There is no OnStartup.txt file to load.
terminate called after throwing an instance of 'std::bad_function_call'
  what():  bad_function_call
Aborted
```

**Comment by Snorelaxed** [comment]
@positiveway, @TauAkiou maybe you guys can help since it seems to be working for you in Ubuntu.
P.S. thanks for your contributions BTW

**Comment by TauAkiou** [comment]
the first thing I will note is that I recommend _not_ running this as root.

i've never used PopOS, so I may have to spin up a VM for testing.

**Comment by Snorelaxed** [comment]
I pulled the master branch today and it seems to work fine. I guess this error was caused by my mistake.
@TauAkiou Thanks for that quick reply though.
