### ISSUE TITLE
Linux Issues

### ISSUE THREAD

**Issue by SusStew** [Electronicks/JoyShockMapper#78]
I've noticed several things that work on Windows but not on Linux.

- Arrow keys don't work in the console for navigating between commands
- You can't bind a button to a .txt config using quotation marks.
- You can't write .txt config in another .txt config to reference it.

Hopefully these issues can be fixed because otherwise this is a great program!

**Comment by Electronicks** [comment]
Linux is not officially supported. You may be able to find help on the community discord Gyro Gaming. If you do find a fix, feel free to suggest a pull request and I will merge it.
