### ISSUE TITLE
DS4: Clicking touchpad without touching capacitive surface causes TOUCH binding to fire rapidly

### ISSUE THREAD

**Issue by BraqueDown** [Electronicks/JoyShockMapper#8]
The touchpad click on the Dualshock 4 can be easily pressed without touching the actual pad surface by pressing the curled edge on top of the controller. This means that CAPTURE can be mapped to its own binding, while chording TOUCH (or T1-T25) with CAPTURE can create more bindings still.

However, clicking the touchpad in this way causes the TOUCH binding to toggle state constantly, causing rapid inputs.

Here is Red Eclipse with `TOUCH = SPACE`:

https://user-images.githubusercontent.com/43602802/119915207-5d414600-bfa5-11eb-95ba-0403ac20e37a.mp4

Out of curiosity, I tried changing `TURBO_PERIOD` to see if it affected anything, which it did not.

**Comment by Electronicks** [comment]
Fixed in v3.1.1
