### ISSUE TITLE
compile failed on ubuntu 18.04 L4T

### ISSUE THREAD

**Issue by z1713299460** [Electronicks/JoyShockMapper#92]
compile failed on ubuntu 18.04 L4T (linux for tegra

failed logs here

[ 48%] Building CXX object JoyShockMapper/CMakeFiles/JoyShockMapper.dir/src/main.cpp.o
/home/clannad/Desktop/JoyShockMapper-3.4.0/JoyShockMapper/src/main.cpp:15:10: fatal error: 'filesystem'
      file not found
#include <filesystem>
         ^~~~~~~~~~~~
1 error generated.
JoyShockMapper/CMakeFiles/JoyShockMapper.dir/build.make:75: recipe for target 'JoyShockMapper/CMakeFiles/JoyShockMapper.dir/src/main.cpp.o' failed
make[2]: *** [JoyShockMapper/CMakeFiles/JoyShockMapper.dir/src/main.cpp.o] Error 1
CMakeFiles/Makefile2:173: recipe for target 'JoyShockMapper/CMakeFiles/JoyShockMapper.dir/all' failed
make[1]: *** [JoyShockMapper/CMakeFiles/JoyShockMapper.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2

environment check log

-- The CXX compiler identification is Clang 6.0.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Checking for one of the modules 'gtk+-3.0'
-- Checking for one of the modules 'appindicator3-0.1'
-- Checking for one of the modules 'libevdev'
-- JSM version is vHEAD-HASH-NOTFOUND.HEAD-HASH-NOTFOUND.HEAD-HASH-NOTFOUND
-- CPM: adding package SDL2@ (release-2.0.20)
-- The C compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done

i have very limited knowledge of compiling program, if someone know how to fix it would be greatly appreciated

**Comment by Electronicks** [comment]
Linux is not officially supported. You may be able to find help on the community discord Gyro Gaming. If you do find a fix, feel free to suggest a pull request and I will merge it.
