### ISSUE TITLE
compiling on arch linux doesnt seem to move files/folders correctly

### ISSUE THREAD

**Issue by spawncampingnoob** [Electronicks/JoyShockMapper#96]
just a warning: i have next to 0 clue as to what i'm doing here, so if i made a really stupid mistake, im sorry

tried compiling the source code on arch linux, the program itself compiles just fine, but the stuff in "/dist" doesn't copy to the right directories, meaning the configs, the .desktop file, the udev thingimajig etc. arent copied to the right directories

i can send a log of the compilation if needed, but looking at the terminal output i dont see anything that would cause this

thanks in advance

**Comment by Electronicks** [comment]
Linux is not officially supported. You may be able to find help on the community discord Gyro Gaming. If you do find a fix, feel free to suggest a pull request and I will merge it.
