### ISSUE TITLE
 [Feature Request] Radial Menus

### ISSUE THREAD

**Issue by jayrfs** [Electronicks/JoyShockMapper#97]
Support for steam input style radial menus would be amazing.

[https://partner.steamgames.com/doc/features/steam_controller/radial_menus](https://partner.steamgames.com/doc/features/steam_controller/radial_menus)

**Comment by Electronicks** [comment]
Radial menus is only possible with on On Screen Overlay, which JSM does not have.

Do be advised that JSM can work in conjunction with Steam Input : as long as JSM's config and SI's config don't overlap, you can use both at the same time, which is my recommendation. With GloSC, you can use Menus on any game.
