### ISSUE TITLE
[Bug] Turbo modifier does not work simulated virtual controller buttons

### ISSUE THREAD

**Issue by jayrfs** [Electronicks/JoyShockMapper#99]
Hi, I found a bug with turbo modifier on virtual controller

```
VIRTUAL_CONTROLLER = XBOX
S = X_A+
```

Expected Behaviour: X_A is pulsed
Observed Behaviour: X_A is continuously held down

I've tried this with both DS4 and XBOX modes, it doesn't work in either of them.

Thanks

**Comment by Electronicks** [comment]
Fixed in v3.5

**Comment by jayrfs** [comment]
I am still facing the same issue on 3.5

**Comment by Electronicks** [comment]
I did some testing. The buttons are released for 40ms which is very short amount of time. Did you try in hand whether it works? Because vscview and the windows panel won't display it properly. 

You can also use both turbo and toggle to have 50-50 press time. It will be visible then

**Comment by jayrfs** [comment]
>Did you try in hand whether it works? 

I tested it in game again and it doesn't seem to work on my end. Either it is pulsing way too fast for the game to detect or it is simply not pulsing at all.

> You can also use both turbo and toggle to have 50-50 press time. It will be visible then
I don't understand this, could you show those commands?

I also tried modifying `TURBO_PERIOD = 1000` to see if that changes anything but that only affects the output in the commandline and doesn't seem to affect actual turbo period for virtual controller.

**Comment by jayrfs** [comment]
fixed as of c5fcf306ce5b6e675b2e165856531ed1d5626732
